MATERIAL_INDEX_TO_NAME = {
    0: 'environment_charges_lakhs',
    1: 'washers_qty (qty)',
    2: 'CT_units',
    3: 'PT_units',
    4: 'min_diesel_litre',
    5: 'earth_wire_km (km)',
    6: 'converter_transformer_oil_liters (liters)',
    7: 'curing_compound_liters (liters)',
    8: 'formwork_oil_liters (liters)',
    9: 'lubrication_grease_kg (kg)',
    10: 'binding_wire_kg (kg)',
    11: 'arcing_horn_units',
    12: 'guy_rope_m (m)',
    13: 'tower_steel_kg (kg)',
    14: 'bolts_nuts_qty (qty)',
    15: 'gravel_tons (tons)',
    16: 'circuit_breaker_units',
    17: 'control_cable_m (m)',
    18: 'paint_liters (liters)',
    19: 'isolator_units',
    20: 'busbar_m (m)',
    21: 'harmonic_filter_units',
    22: 'vibration_dampers_units',
    23: 'backfill_soil_cum (m3)',
    24: 'switchgear_units',
    25: 'cement_bags (bags)',
    26: 'hardware_fittings_units',
    27: 'spacers_units',
    28: 'excavated_soil_cum (m3)',
    29: 'shuttering_steel_sqm (sqm)',
    30: 'clamps_units',
    31: 'jumpers_m (m)',
    32: 'conductor_km (km)',
    33: 'water_liters (liters)',
    34: 'extra_insulator_units',
    35: 'OPGW_km (km)',
    36: 'galvanized_coating_kg (kg)',
    37: 'concrete_mix_cum (m3)',
    38: 'spare_bolts_kg (kg)',
    39: 'spare_clamps_units',
    40: 'spare_conductor_m (m)',
    41: 'reinforcement_steel_kg (kg)',
    42: 'packing_material_kg (kg)',
    43: 'ladder_units',
    44: 'insulator_discs_units',
    45: 'spare_OPGW_m (m)',
    46: 'DC_cable_km (km)',
    47: 'earthing_rod_units',
    48: 'stay_wire_kg (kg)',
    49: 'cross_arm_units',
    50: 'thyristor_valve_units',
    51: 'transformer_oil_liters (liters)',
    52: 'tower_parts_units',
    53: 'safety_equipment_units',
    54: 'spare_hardware_kg (kg)',
    55: 'sand_tons (tons)',
    56: 'smoothing_reactor_units',
    57: 'shuttering_wood_sqm (sqm)',
    58: 'aggregate_tons (tons)',
    59: 'earthing_cable_m (m)',
    60: 'voltage_kv',
    61: 'duration_months',
    62: 'angle_steel_sections_kg',
    63: 'tower_legs_kg',
    64: 'tower_body_members_kg',
    65: 'extension_pieces_kg',
    66: 'pack_plates_kg',
    67: 'environment_charges_lakhs_price',
    68: 'washers_qty (qty)_price',
    69: 'CT_units_price',
    70: 'PT_units_price',
    71: 'min_diesel_litre_price',
    72: 'earth_wire_km (km)_price',
    73: 'converter_transformer_oil_liters (liters)_price',
    74: 'curing_compound_liters (liters)_price',
    75: 'formwork_oil_liters (liters)_price',
    76: 'lubrication_grease_kg (kg)_price',
    77: 'binding_wire_kg (kg)_price',
    78: 'arcing_horn_units_price',
    79: 'guy_rope_m (m)_price',
    80: 'tower_steel_kg (kg)_price',
    81: 'bolts_nuts_qty (qty)_price',
    82: 'gravel_tons (tons)_price',
    83: 'circuit_breaker_units_price',
    84: 'control_cable_m (m)_price',
    85: 'paint_liters (liters)_price',
    86: 'isolator_units_price',
    87: 'busbar_m (m)_price',
    88: 'harmonic_filter_units_price',
    89: 'vibration_dampers_units_price',
    90: 'backfill_soil_cum (m3)_price',
    91: 'switchgear_units_price',
    92: 'cement_bags (bags)_price',
    93: 'hardware_fittings_units_price',
    94: 'spacers_units_price',
    95: 'excavated_soil_cum (m3)_price',
    96: 'shuttering_steel_sqm (sqm)_price',
    97: 'clamps_units_price',
    98: 'jumpers_m (m)_price',
    99: 'conductor_km (km)_price',
    100: 'water_liters (liters)_price',
    101: 'extra_insulator_units_price',
    102: 'OPGW_km (km)_price',
    103: 'galvanized_coating_kg (kg)_price',
    104: 'concrete_mix_cum (m3)_price',
    105: 'spare_bolts_kg (kg)_price',
    106: 'spare_clamps_units_price',
    107: 'spare_conductor_m (m)_price',
    108: 'reinforcement_steel_kg (kg)_price',
    109: 'packing_material_kg (kg)_price',
    110: 'ladder_units_price',
    111: 'insulator_discs_units_price',
    112: 'spare_OPGW_m (m)_price',
    113: 'DC_cable_km (km)_price',
    114: 'earthing_rod_units_price',
    115: 'stay_wire_kg (kg)_price',
    116: 'cross_arm_units_price',
    117: 'thyristor_valve_units_price',
    118: 'transformer_oil_liters (liters)_price',
    119: 'tower_parts_units_price',
    120: 'safety_equipment_units_price',
    121: 'spare_hardware_kg (kg)_price',
    122: 'sand_tons (tons)_price',
    123: 'smoothing_reactor_units_price',
    124: 'shuttering_wood_sqm (sqm)_price',
    125: 'aggregate_tons (tons)_price',
    126: 'earthing_cable_m (m)_price',
    127: 'angle_steel_sections_kg_price',
    128: 'tower_legs_kg_price',
    129: 'tower_body_members_kg_price',
    130: 'extension_pieces_kg_price',
    131: 'pack_plates_kg_price',
}
